services:
  - type: web
    name: casaway-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    repo: https://github.com/Uscout07/casaway_backend
    branch: main
    rootDir: .
